**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [1]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [3]:
#Code here
a = np.array([np.nan for i in range (10)])
a[4] = 1
a

array([nan, nan, nan, nan,  1., nan, nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [12]:
#Code here
a, b = map(int, input("Enter two numbers seperated by space ").split())
np.random.random((b,a))

array([[0.5395198 , 0.35032767],
       [0.3741839 , 0.49169924],
       [0.26308006, 0.51695718],
       [0.77488225, 0.63989381],
       [0.66156091, 0.22364526]])

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [15]:
#Code here
a = np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [16]:
#Code here
np.random.random((10))

array([0.4577213 , 0.96175871, 0.14241735, 0.58070241, 0.85798728,
       0.11301663, 0.75679699, 0.7566345 , 0.32355336, 0.10732717])

In [18]:
np.linspace(0,1,10, dtype= int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [28]:
#Code here
np.eye(3,4)
np.hstack((np.identity(3), np.zeros((3,1))))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [33]:
#Code here
np.vstack((np.arange(0,5), np.arange(0,5)))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [37]:
#code here
np.random.randint(1,100,20).reshape(10,2)

array([[85, 34],
       [23, 92],
       [38, 69],
       [28, 21],
       [54, 32],
       [32,  4],
       [ 1, 34],
       [92, 34],
       [13, 28],
       [46, 30]])

###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [39]:
#Code here


### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [50]:
#Code here
nums = input("Enter nos ").split()
a = np.array(nums, dtype = int)
a[::-1]

array([3, 2, 1])

### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [52]:
#Code here
np.array([1,2]).size

2

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [56]:
#Code here
a = [33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278]
b = np.array(a)
np.exp(b)/np.exp(b).sum()

array([4.57181033e-26, 1.16249922e-20, 7.73872594e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01])

### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [ ]:
#Coder here
a = 1
b = []
while a!=0 or a!='0':
    a = [input("keep entering arrays ").split()]
    b.append(a)
np.vstack(b.items)    

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [ ]:
#Code here

###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [ ]:
#Code here

###`Q-16:` Replace odd elements in arrays with -1.

In [ ]:
#Code here

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [ ]:
#Code here

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [2]:
# Given
import numpy as np
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[9936, 2105, 9379, 8253, 8631],
       [6704, 4553, 7337, 6891, 3679],
       [3167, 1794, 4114, 2764, 2334],
       [2757, 1210, 4486, 2411, 2987],
       [4678, 1543, 2988, 9425, 7230],
       [1852, 5850, 8604, 6264,  228],
       [  21, 7059, 4690, 6988, 9643],
       [3316, 9444, 6607, 6493, 8397]])

In [3]:
#Code here
for i in range(0,arr1.shape[1],2):
    print(arr1[:,[i]].min())
    print(arr1[:,[i]].max())
    arr1[:,[i]] = (arr1[:,[i]] - arr1[:,[i]].min()) / (arr1[:,[i]].max() - arr1[:,[i]].min())

arr1

21
9936
2988
9379
228
9643


array([[   1, 2105,    1, 8253,    0],
       [   0, 4553,    0, 6891,    0],
       [   0, 1794,    0, 2764,    0],
       [   0, 1210,    0, 2411,    0],
       [   0, 1543,    0, 9425,    0],
       [   0, 5850,    0, 6264,    0],
       [   0, 7059,    0, 6988,    1],
       [   0, 9444,    0, 6493,    0]])

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [6]:
#Code here
def func(arr, n):
    if n>len(arr):
        return -1
    return sorted(arr, reverse= True)[n-1]

arr1 = [12, 30, 40, 7, 10]
func(arr1, 3)

12

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [14]:
#code here
a = np.array([1,2,3])
[a[i] for i in range (3) for j in range(3)] + [a[i] for j in range (3) for i in range(3)]

[1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]